openapi: 3.0.0
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: 1.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: '#/definitions/Login'
            produces:
                - application/json
            responses:
                '200':
                    description: Login Successfully
                    schema:
                        $ref: '#/definitions/LoginResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: '#/definitions/User'
            produces:
                - application/json
            responses:
                '200':
                    description: Signup Successfully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/profile:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  type: string
                  required: true
            produces:
                - application/json
            responses:
                '200':
                    description: User profile retrieved successully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  type: string
                  required: true
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: '#/definitions/UserProfile'
            produces:
                - application/json
            responses:
                '200':
                    description: User profile retrieved successully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/transactions:
        get:
            security:
                - Bearer: []
            tags:
                - All user transactions
            summary: Retrieves all user transactions
            description: API to retrieve all user month's transactions
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                '200':
                    description: successful operation
                    schema:
                        $ref: '#/definitions/TransactionsResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/transactions/{transactionId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Retrieves a specific user transaction
            description: API to retrieve a user's transaction over the current month
            parameters:
                - in: path
                  name: transactionId
                  description: 'ID of the transaction that needs to be get '
                  required: true
                  type: integer
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                '200':
                    description: successful operation
                    schema:
                        $ref: '#/definitions/TransactionResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/transaction/{transactionId}:
        patch:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Updates an informative note or a category type from a transaction
            description: >-
                API in order to up to date a specific transaction's note or a specific
                transaction's category type
            parameters:
                - in: path
                  name: transactionId
                  description: 'ID of the transaction that needs to be get '
                  required: true
                  type: integer
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Value Payload
                  required: true
                  schema:
                      $ref: '#/definitions/EditTransaction'
            produces:
                - application/json
            responses:
                '200':
                    description: successful operation
                    schema:
                        $ref: '#/definitions/TransactionResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    LoginResponse:
        type: object
        properties:
            token:
                type: string
    TransactionsResponse:
        type: object
        properties:
            response:
                $ref: '#/definitions/ApiTransactionResponse'
            body:
                type: object
                properties:
                    id:
                        type: integer
                    email:
                        type: string
                    transactions:
                        type: array
                        items:
                            $ref: '#/definitions/Transaction'
    TransactionResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                $ref: '#/definitions/Transaction'
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
    UserProfile:
        type: object
        properties:
            firstName:
                type: string
            lastName:
                type: string
    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
    Transaction:
        type: object
        properties:
            id:
                type: integer
            amount:
                type: integer
            date:
                type: string
            description:
                type: string
            balance:
                type: integer
            transactionType:
                type: string
            tag:
                type: string
            notes:
                type: string
    EditTransaction:
        type: object
        properties:
            notes:
                type: string
            tag:
                type: string
    ApiTransactionResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
    ApiResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/marjoriesiad/ArgentBank/1.0.0